flow-hydraulics/flow-wallet-api

accounts/config.go, accounts/service.go, templates/template_strings/transactions.go
The script that adds weightless proposal keys assumes the admin key is at index 0. This assumption is sometimes wrong and we should refer to the `ADMIN_KEY_INDEX` environment variable to know which index holds the admin key.
=> Make admin key index configurable for creating proposal keys

index.html
Use the new repo URL for the OpenAPI spec in the HTML docs.
=> Update spec URL for HTML docs (ReDoc)

api/scripts.http, api/tokens.http, api/transaction.http, main.go, tokens/chain_events.go, tokens/service.go, tokens/store_gorm.go, tokens/tokens.go, transactions/service.go, transactions/store_gorm.go, transactions/transactions.go
As per this change we needed to migrate away from the incorrect assumption that the payer is also the "sender" of a token transfer. 
- Renaming `PayerAddress` to `ProposerAddress` in `Transaction`
- Adding a `SenderAddress` column to `TokenTransfer`
- Migrating so changes should be invisible to users
=> Admin as payer on all outgoing transactions

Makefile, chain_events/lib.go, chain_events/listener.go, chain_events/store.go, chain_events/store_gorm.go, configs/configs.go, docker-compose.yml, main.go
- Resolves #177
- Locks the status row in database so only one poller can run at a time, others will just skip
- Makes *starting height*, *max blocks to check* and *polling interval* configurable
=> Refactor event polling

tests/common.go, tests/internal/test/config.go, tests/internal/test/flow_client.go, tests/internal/test/logger.go, tests/internal/test/service.go, tests/transaction_service_test.go, transactions/service.go, transactions/transactions.go
`transactions.Service.Sign()` crafts a Flow transaction and signs it
with given account key. It returns pre-signed transaction that can be
sent later separately.
This PR also suggests a new structure for integration tests so that they
are laid out more fine grained and can include a bit more support
code that is packaged separately.
The idea is that `tests` package holds all integration tests, whether
those test service implementations or fully e2e implementations via
REST API (such as corresponding signing endpoint in a follow-up PR).
Towards https://github.com/flow-hydraulics/flow-wallet-api/issues/159
=> Add support for pre-signing a transaction

accounts/service.go, main.go, main_test.go
`templates.Service` is an unused dependency for `accounts.Service`. Drop
it so there's one dependency less :)
=> Drop unused dependency from `accounts.Service`

.github/workflows/test.yml, Makefile, handlers/handlers.go, keys/basic/keys.go, main_test.go, tests/internal/test/config.go, tests/internal/test/flow.go, tests/internal/test/service.go, transactions/service.go
- Bring back `AdminProposalKey` in transactions service. This is needed to allow usage of multiple admin keys.
- Clean up tests and run them with `-p 1` to disable parallel runs
=> Use AdminProposalKey again and make tests more deterministic, 

.dockerignore, Makefile, accounts/service.go, configs/configs.go, flow/cadence/transactions/custom_create_account.cdc, main_test.go
This will add a config parameter for custom account create script: `FLOW_WALLET_SCRIPT_PATH_CREATE_ACCOUNT`
If you want to use the default script, leave this empty (either do not declare it or use "").
fixes #103
Replaces PR #194
=> Basic custom account create script

README.md, accounts/service.go, configs/configs.go, jobs/jobs.go, jobs/jobs_test.go, jobs/notification.go, jobs/options.go, jobs/workerpool.go, main.go, transactions/service.go
Allow users to set a URL which receives job status updates as a webhook. The endpoint should accept `POST` requests of type `application/json` and always respond with a status code of 200.
resolves #180
=> Add job status update via webhook

.dockerignore, accounts/service.go, configs/configs.go, jobs/jobs_test.go, jobs/notification.go, jobs/options.go, jobs/workerpool.go, main.go, tests/workerpool_test.go, transactions/service.go
Previously the webhook functionality would prevent the application from exiting if the webhook endpoint does not respond to the request. This PR adds a timeout for the webhook request and adds a context to job execute functions, allowing cancellation of job executions from main.
=> Add context to workerpool, timeout to webhook

MIGRATIONS.md, accounts/accounts.go, accounts/service.go, accounts/store_gorm.go, keys/aws/aws.go, keys/google/google.go, keys/keys.go, main_test.go, migrations/internal/m20211118/migration.go, migrations/migrations.go, openapi.yml
Changes in this PR:
- public keys are stored in the database for custodial accounts at creation time, migration script included
- keys are returned in the account creation response (sync) & account details response, private keys are omitted
- keys stored in a KMS have hashAlgo & signAlgos set (they were `UNKNOWN` previously)
- fixed linter warning about redundant type from array
Resolves #97
=> Store public keys in database, fix missing algos for KMS keys

.env.example, accounts/options.go, accounts/service.go, configs/configs.go, go.mod, go.sum, main.go, transactions/options.go, transactions/service.go
- Add `FLOW_WALLET_MAX_TPS` env var to control max send rate, defaults to 10 (per second)
- Fix account creation proposal key errors
resolves #105
=> Allow throttling the transaction send rate

openapi.yml
Added `type` to account component in openapi.yaml as it was missing.
=> Add type to account component

.gitignore, Makefile, README.md, api-test-scripts/account.http, api-test-scripts/raw_transactions.http, api-test-scripts/system.http, api-test-scripts/tokens.http, configs/configs.go, docker-compose.yml, go.mod, go.sum, handlers/handlers.go, handlers/idempotency.go, main.go, migrations/internal/m20211202/migration.go, migrations/migrations.go, openapi.yml, redis-config/redis.conf, redis-config/users.acl, tests/middleware_test.go
This adds basic idempotency middleware for `POST` endpoints:
- only the idempotency key is stored, so the payload is not examined when checking the received idempotency key and hence only `409` can be returned (key already used). A `422` response would require storing the payload.
- there are 3 supported "databases" (see README for configuration):
- `local`: in-memory, single instance only, mainly for testing purposes
- `shared`:  use the same db as main app
- `redis`: use a separate Redis instance
- keys expire after 1 hour, meaning the same key can be used after >1 hour after previous usage
- key is expected to be sent in the `Idempotency-Key` header (OpenAPI spec has been updated accordingly)
Resolves #185
=> Add idempotency middleware

chain_events/listener.go, docker-compose.yml, errors/errors.go, errors/errors_test.go, jobs/jobs_test.go, jobs/workerpool.go, main_test.go, migrations/internal/m20211130/migration.go, migrations/internal/m20211213/migration.go, migrations/internal/m20211221_2/migration.go, migrations/migrations.go, system/options.go, system/service.go, system/system.go, tests/internal/test/flow.go, tests/system_test.go
If a job or event poll fails due to a flow AccessAPI connection error (GRPC error of `ResourceExhausted`, `Internal` or `Unavailable`), the system is paused.
- If the error happened during a job execution, the job will be returned to the pool.
- If the error happened during event polling, the system will retry the same blocks later. 
The system will be paused for 1 minute and no jobs or events will be handled during that time. After the grace period (1 minute), the system is resumed. 
In more detail, the system is paused by setting the `paused_since` timestamp on the system settings database table. 
TODO:
- ~Make sure we correctly detect chain offline situation~
- Add a test to for the grace period
=> Handle situation when chain is unreachable

tests/tokens_service_test.go, tokens/service.go
Fixed error handling of `Setup` function of token service which was causing panic when specified account address was not found in db.  
```shell
wallet-api-1  | time="2021-12-26T08:49:12Z" level=warning msg="Error while handling request" error="error while getting new transaction: error while building transaction: error while getting user authorizer: client: rpc error: code = NotFound desc = could not find account with address 01cf0e2f2f715450"
wallet-api-1  | time="2021-12-26T08:49:12Z" level=info msg="HTTP request" duration=17.016 method=POST path="/v1/accounts/0x01cf0e2f2f715450/non-fungible-tokens/TestToken?sync=" remote="172.20.0.1:58168" size=203 status=400 user-agent=axios/0.24.0
wallet-api-1  | panic: runtime error: invalid memory address or nil pointer dereference
wallet-api-1  | …
```
=> Fixed token setup error handling

.dockerignore, Makefile, README.md, chain_events/listener.go, docker-compose.dev.yml, docker-compose.test-suite.yml, docker-compose.yml, docker/flow-cli/Dockerfile, docker/wallet/Dockerfile, tests/test/config.go
=> Dockerized e2e test suite

jobs/workerpool.go
Fixed: https://github.com/flow-hydraulics/flow-wallet-api/issues/260
Fixed issue with rescheduling jobs. The cause of the problem was the use of pointer when sending jobs to channel.
The previous implementation was sending pointer of `j` to channel and it resulted in that queued jobs reference same address.
So I fixed to send each job's pointer to channel.
```go
for _, j := range jobs {
wp.tryEnqueue(&j, true)
}
```
```go
for i := range jobs {
wp.tryEnqueue(&jobs[i], true)
}
```
=> Fix enqueue jobs

docker/wallet/Dockerfile, go.mod
- Update Go version for the `go.mod`
- Since this project [already uses `1.17` for the tests](https://github.com/flow-hydraulics/flow-wallet-api/blob/3db40e1df7525e40f2480d28a57b1f00f3c95e5b/.github/workflows/test.yml#L22-L22), it would be better to use 1.17 for go.mod as well.
- Fix Go container image version on the Dockerfile.
- Basically, it would be better to fix the image version as much as possible for reproducible builds.
=> Update Go to 1.17

Makefile, docker-compose.dev.yml, docker-compose.test-suite.yml
=> Persist emulator in test-suite, pause containers

.github/workflows/test.yml, jobs/jobs_test.go, jobs/store.go, jobs/store_gorm.go, jobs/workerpool.go, main_test.go, migrations/internal/m20211220/migration.go, tests/test/service.go
Related to https://github.com/flow-hydraulics/flow-wallet-api/issues/241 https://github.com/flow-hydraulics/flow-wallet-api/issues/94
Added `AcceptJob` to job store which updates job as `ACCEPTED` in transaction.
This feature will prevent jobs from being executed multiple times concurrently.
=> Add AcceptJob

accounts/jobs.go, accounts/service.go, accounts/store.go, accounts/store_gorm.go, api-test-scripts/system.http, handlers/accounts.go, handlers/accounts_func.go, main.go, openapi.yml, templates/template_strings/transactions.go, tests/test/service.go
This adds a new endpoint `POST /v1/system/sync-account-key-count`, that will sync the key count for one given address i.e. add copies of the account key if needed (e.g. when `DefaultAccountKeyCount` has been changed).
=> Add "sync key count for existing account" endpoint

flow_helpers/flow_helpers.go
When there is gap between sealed block height and finalized block height, the tx which refers to sealed block height will immediately expire and fail. I observed that some of the txs were failing with error below. 
```
client: rpc error: code = InvalidArgument desc = invalid transaction: transaction is expired: ref_height=60118263 final_height=60119981
```
To avoid this error, it is safer to always refer to finalized block height for new transactions according to https://github.com/onflow/flow-go/pull/1607.
FYI: tx expires if its reference block height is 600 blocks behind the latest finalized block height.
> A transaction expires after 600 blocks are committed on top of the reference block, which takes about 10 minutes at average Mainnet block rates
ref: …
=> Use latest finalized block for reference

chain_events/listener.go, configs/configs.go, jobs/workerpool.go, main.go
1. Add some extra logging. It's very helpful to debug rpc related issues. For example, only with this extra logging we found following error: grpc: received message larger than max (4296233 vs. 4194304)
2. Add more flexibility by passing some of hardcoded params of workerpool to config: MaxJobErrorCount, DBJobPollInterval, AcceptedGracePeriod, ReSchedulableGracePeriod.
3. Pass hardcoded PauseDuration to config.
4. Add new config param GrpcMaxCallRecvMsgSize(default 16777216). Fix of error: grpc: received message larger than max (4296233 vs. 4194304).
=> Make some worker & service consts configurable.
